app/mod/views.py
from urllib2 import Request, urlopen, URLError
from app.mod.models import *
from flask import Blueprint, g, redirect, url_for, session, request, flash, render_template, jsonify
from flask_login import login_required, current_user
import json

mod = Blueprint('mod', __name__, url_prefix='', template_folder='templates', static_folder='static')


@mod.before_request
def before_request():
    g.user = current_user


@mod.route('/')
def index():
    if current_user.is_authenticated:
        return render_template('index.html', user=g.user, title='Home',
                               Teachers=Teachers, Students=Students, Admins=Administrators)
    else:
        redirect(url_for('auth.login'))
    access_token = session.get('access_token')
    if access_token is None:
        return redirect(url_for('auth.login'))
    access_token = access_token[0]
    headers = {'Authorization': 'OAuth ' + access_token}
    req = Request('https://www.googleapis.com/oauth2/v1/userinfo',
                  None, headers)
    try:
        res = urlopen(req)
    except URLError, e:
        if e.code == 401:
            # Unauthorized - bad token
            session.pop('access_token', None)
            return redirect(url_for('auth.login'))
        return res.read()
    return redirect(url_for('auth.login'))


@mod.route('/my_record_book')
@login_required
def my_record_book():
    if not Students.query.filter_by(email=g.user.email).first():
        return render_template('Unauthorized.html', user=g.user,
                               title='Error')
    user = Students.query.filter_by(email=g.user.email).first().id
    stats = Statement.query.filter_by(student_id=user)
    return render_template('my_record_book.html',
                           user=g.user,
                           title='Statement',
                           stats=stats,
                           marks=Marks,
                           Teachers=Teachers,
                           Students=Students,
                           Admins=Administrators)


@mod.route('/administration')
@login_required
def administration():
    if not Administrators.query.filter_by(email=g.user.email).first():
        return render_template('Unauthorized.html', user=g.user,
                               title='Error')
    return render_template('administration.html', user=g.user,
                           title='Administration', Teachers=Teachers, Students=Students, Admins=Administrators)


@mod.route('/teacher_panel')
@login_required
def teacher_panel():
    if not Teachers.query.filter_by(email=g.user.email).first():
        return render_template('Unauthorized.html', user=g.user,
                               title='Error')
    return render_template('teacher_panel.html',
                           user=g.user,
                           title='Teacher Panel',
                           Teachers=Teachers,
                           Students=Students,
                           Admins=Administrators)


@mod.route('/create_statement', methods=['GET', 'POST'])
@login_required
def create_statement():
    if request.method == 'POST':
        specialization = request.form.get('statement_specialization')
        teacher = request.form.get('statement_teacher')
        subject = request.form.get('statement_subject')
        number = request.form.get('statement_number')
        course = request.form.get('statement_course')
        control = request.form.get('statement_control_form')
        if specialization and teacher and subject and number and course and control is not None:
            statement = Allstatements(number, subject, teacher, control, specialization, course)
            db.session.add(statement)
            db.session.commit()
        if statement is not None:
            students = Students.query.all()
            for s in students:
                if s.specialization_id == statement.specialization and s.course == statement.course:
                    student_statement = Statement(number, control, s.id, subject, teacher, '', '')
                    db.session.add(student_statement)
                    db.session.commit()
                else:
                    flash('Something is missing')
            flash('Statement created successfully')
            return redirect(url_for('mod.index'))
    teacher_list = Teachers.query.all()
    subjects = Subjects.query.all()
    controlforms = Controlforms.query.all()
    specializations = Specializations.query.all()
    return render_template('create_statement.html',
                           user=g.user,
                           title='Create Statement',
                           Teachers=Teachers,
                           Students=Students,
                           Admins=Administrators,
                           TeacherList=teacher_list,
                           SubjectList=subjects,
                           ControlFormList=controlforms,
                           SpecializationList=specializations)


@mod.route('/show_statement', methods=['GET', 'POST'])
@login_required
def show_statement():
    teacher = Teachers.query.filter_by(email=g.user.email).first().id
    statements = Allstatements.query.filter_by(teacher=teacher)
    return render_template('show_statement.html',
                           state=statements,
                           user=g.user,
                           title='Statements List',
                           Teachers=Teachers,
                           Students=Students,
                           Admins=Administrators)


@mod.route('/show_statement/<statement_view>')
@login_required
def statements(statement_view):
    selected_statement = Allstatements.query.filter_by(statement_number=statement_view).first()
    statement = Statement.query.all()
    return render_template('view_statement.html',
                           user=g.user,
                           title='View Statement',
                           marks=Marks,
                           stats=statement,
                           state=selected_statement,
                           Teachers=Teachers,
                           Students=Students,
                           Admins=Administrators)


@mod.route('/statements_list')
@login_required
def statements_list():
    teacher = Teachers.query.filter_by(email=g.user.email).first().id
    statements = Allstatements.query.filter_by(teacher=teacher)
    return render_template('statements_list.html',
                           state=statements,
                           user=g.user,
                           title='Statements List',
                           Teachers=Teachers,
                           Students=Students,
                           Admins=Administrators)


@mod.route('/statements_list/<name>', methods=['GET', 'POST'])
@login_required
def statement(name):
    selected_statement = Allstatements.query.filter_by(statement_number=name).first()
    stats = Statement.query.all()
    if request.method == 'POST':
        date = request.form.get('date')
        for s in stats:
            if s.statement_id == selected_statement.statement_number and s.subject_id == selected_statement.subject:
                abd = s.student_id
                mark = str(abd)
                student_id = str(abd * 200)
                mark = request.form.get(mark)
                student = request.form.get(student_id)
                g.temp = Statement.query.filter_by(subject_id=s.subject_id).filter_by(student_id=student).first()
                g.temp.date = date
                if not g.temp.mark:
                    g.temp.mark = mark
                    db.session.add(g.temp)
                    db.session.commit()
        g.tmp = selected_statement
        g.tmp.closed = 'closed'
        g.tmp.date = date
        db.session.add(g.tmp)
        db.session.commit()
        return redirect(url_for('mod.statements', statement_view=selected_statement.statement_number))
    return render_template('statement.html',
                           user=g.user,
                           title='Statement',
                           state=selected_statement,
                           stats=stats,
                           Teachers=Teachers,
                           Students=Students,
                           Admins=Administrators)


@mod.route('/get_the_subject/<int:statement_specialization>/<int:statement_course>', methods=['GET'])
@login_required
def get_the_subject(statement_specialization, statement_course):
    subjects = Subjects.query.filter_by(specialization_id=statement_specialization).filter_by(course=statement_course)
    to_json = {}
    for subject in subjects:
        dict = {subject.id: subject.subject_name}
        to_json.update(dict)
    dumped_json = json.dumps(to_json)
    return dumped_json


@mod.route('/get_the_teachers/<int:subject>', methods=['GET'])
@login_required
def get_the_teachers(subject):
    teachers = Subjectteachers.query.filter_by(subjects_id=subject)
    to_json = {}
    for teacher in teachers:
        dict = {teacher.teachers_id: teacher.teacher_subject.name}
        to_json.update(dict)
    dumped_json = json.dumps(to_json)
    return dumped_json


@mod.route('/record_book_api/<string:email>', methods=['GET'])
def record_book_api(email):
    to_json = {}
    print email
    student = Students.query.filter_by(email=email).first()
    for S in Statement.query.filter_by(student_id=student.id):
        control_form = S.control_form.form
        if control_form == 'Exam':
            mark = S.statement_mark.examen_mark
        else:
            mark = S.statement_mark.credit_mark
        dict = {S.subject_id: {"subject": S.subject_statement.subject_name,
                               "teacher": S.teacher_statement.name,
                               "control_form": control_form,
                               "mark": {
                                   "points": S.mark,
                                   "letter": S.statement_mark.letter,

app/templates/Unauthorized.html
{% extends 'base.html' %}
{% block content %}
    <div class="text-center m-t-lg">
        <h3>Помилка. Ви не маєте доступу до цієї сторінки, будь-ласка, авторизуйтеся за допомогою коректного адресу електронної пошти</h3>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Home</title>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link href="../static/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="../static/css/animate.css" rel="stylesheet">
    <link href="../static/css/style.css" rel="stylesheet">

</head>

<body>
    {% if not current_user.is_authenticated %}
        <p style="font-family: Impact; font-size: 24px; color: #2a6496; text-align: center; margin-top: 200px ">
            You are not logged in, you need to join to the dark side to view this page...Also, we got a cookies:)))</p>
        <br><a href="login" ><img style="margin-left: 480px; border-radius: 0px" src="/static/image/signin.png"></a>
    {% endif %}
<div id="wrapper">

    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element">
                        {% block content %}
                            <img class=avatar src={{ user.avatar }}>
                            {% if Students.query.filter_by(email=user.email).first() %}
                                <span class="clear"> <span class="block m-t-xs">
                                    <strong class="font-bold">{{ Students.query.filter_by(email=user.email).first().name }}</strong>
                                                    </span>
                                    </span>
                            {% elif Teachers.query.filter_by(email=user.email).first()%}
                                <img class=avatar src={{ user.avatar }}>
                                <span class="clear"> <span class="block m-t-xs">
                                    <strong class="font-bold">{{ Teachers.query.filter_by(email=user.email).first().name }}</strong>
                                                    </span>
                                    </span>
                            {% endif %}
                        {% endblock %}

                    </div>
                    <div class="logo-element">

                    </div>
                </li>
                <li>
                    <a href="/"><i class="fa fa-th-large"></i> <span class="nav-label">Головна</span></a>
                </li>
                <li class="active">
                    <a href="my_record_book"><i class="fa fa-th-large"></i> <span class="nav-label">Моя залiкова книжка</span> </a>
                </li>
            </ul>

        </div>
    </nav>

    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    <form role="search" class="navbar-form-custom" method="post" action="#">
                    </form>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <a href="logout">
                            <i class="fa fa-sign-out"></i> Log out
                        </a>
                    </li>
                </ul>

            </nav>
        </div>
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="text-center m-t-lg">
                        <a href="create_statement">Створити відомість</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- Mainly scripts -->
<script src="../static/js/jquery-2.1.1.js"></script>
<script src="../static/js/bootstrap.min.js"></script>
<script src="../static/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="../static/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="../static/js/inspinia.js"></script>
<script src="../static/js/plugins/pace/pace.min.js"></script>


</body>

</html>

app/templates/flash.html
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

app/templates/index.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Home</title>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link href="../static/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="../static/css/animate.css" rel="stylesheet">
    <link href="../static/css/style.css" rel="stylesheet">

</head>

<body>

<div id="wrapper">

    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element">
                        {% block content %}
                            <img class=avatar src={{ user.avatar }}>
                            {% if Students.query.filter_by(email=user.email).first() %}
                                <span class="clear"> <span class="block m-t-xs">
                                    <strong class="font-bold">{{ Students.query.filter_by(email=user.email).first().name }}</strong>
                                                    </span>
                                    </span>
                            {% elif Teachers.query.filter_by(email=user.email).first()%}
                                <img class=avatar src={{ user.avatar }}>
                                <span class="clear"> <span class="block m-t-xs">
                                    <strong class="font-bold">{{ Teachers.query.filter_by(email=user.email).first().name }}</strong>
                                                    </span>
                                    </span>
                            {% endif %}
                        {% endblock %}

                    </div>
                    <div class="logo-element">

                    </div>
                </li>
                <li class="active">
                    <a href="/"><i class="fa fa-th-large"></i> <span class="nav-label">Головна</span></a>
                </li>

                    {% if Students.query.filter_by(email=user.email).first() %}
                            <li><a id="coverin" class="fa fa-th-large" href="{{ url_for('mod.my_record_book') }}"><span class="nav-label"> Моя залікова книжка</span></a></li>
                    {% endif %}
                    {% if Teachers.query.filter_by(email=user.email).first() %}
                            <li><a id="coverin" class="fa fa-th-large" href="{{ url_for('mod.teacher_panel') }}"><span class="nav-label"> Панель викладача</span></a></li>
                    {% endif %}
                    {% if Admins.query.filter_by(email=user.email).first() %}
                            <li><a id="coverin" class="fa fa-th-large" href="{{ url_for('mod.administration') }}"><span class="nav-label"> Панель адміністратора</span></a></li>
                    {% endif %}

            </ul>

        </div>
    </nav>

    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    <form role="search" class="navbar-form-custom" method="post" action="#">
                    </form>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <a href="logout">
                            <i class="fa fa-sign-out"></i> Log out
                        </a>
                    </li>
                </ul>

            </nav>
        </div>
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="text-center m-t-lg">
                            {% if Students.query.filter_by(email=user.email).first() %}
                                <span class="clear"> <span class="block m-t-xs">
                                        <h1>Факультет: {{ Students.query.filter_by(email=user.email).first().specialization.faculty.faculty_name }}</h1>
                                                        </span>
                                    </span>
                                <span class="clear"> <span class="block m-t-xs">
                                        <h1>Спецiалiзацiя: {{ Students.query.filter_by(email=user.email).first().specialization.cafedra_name }}</h1>
                                                        </span>
                                    </span>
                                <span class="clear"> <span class="block m-t-xs">
                                        <h1>Курс: {{ Students.query.filter_by(email=user.email).first().course }}</h1>
                                                        </span>
                                    </span>
                                <span class="clear"> <span class="block m-t-xs">
                                        <h1>Група: {{ Students.query.filter_by(email=user.email).first().course*100 + Students.query.filter_by(email=user.email).first().specialization.code }}</h1>
                                                        </span>
                                    </span>
                            {% elif Teachers.query.filter_by(email=user.email).first()%}
                                <span class="clear"> <span class="block m-t-xs">
                                        <h1>Факультет: {{ Teachers.query.filter_by(email=user.email).first().teacher_cafedra.teacher_caf.faculty_name }}</h1>
                                                        </span>
                                    </span>
                                <span class="clear"> <span class="block m-t-xs">
                                        <h1>Кафедра: {{ Teachers.query.filter_by(email=user.email).first().teacher_cafedra.cafedra_name }}</h1>
                                                        </span>
                                    </span>
                                <span class="clear"> <span class="block m-t-xs">
                                        <h1>Звання: {{ Teachers.query.filter_by(email=user.email).first().teacher_degree.degree_name }}</h1>
                                                        </span>
                                </span>
                            {% endif %}
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- Mainly scripts -->
<script src="../static/js/jquery-2.1.1.js"></script>
<script src="../static/js/bootstrap.min.js"></script>
<script src="../static/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="../static/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="../static/js/inspinia.js"></script>
<script src="../static/js/plugins/pace/pace.min.js"></script>


</body>

</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <p>You are not logged in, please, use Google OAuth</p>
    <a href="{{ url_for(auth.authorized) }}">Login</a>
</body>
</html>